run-dist:
	./build/install/app/bin/app
install-dist:
	./gradlew installDist
clean:
	./gradlew clean
lint:
	./gradlew checkstyleMain
test:
	./gradlew checkstyleTest
build-run:
	./gradlew build run
report:
	./gradlew jacocoTestReport

.PHONY: build